config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobs

  root 'jobs#index'

  devise_scope :user do
   get "signup", to: "devise/registrations#new"
   get "login", to: "devise/sessions#new"
   get "logout", to: "devise/sessions#destroy"
  end
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user

  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base

  mount_uploader :avatar, AvatarUploader
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs, dependent: :destroy
  belongs_to :category

  # User Avatar Validation
  validates_integrity_of  :avatar
  validates_processing_of :avatar
 
  private
    def avatar_size_validation
      errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up){ |u| u.permit(:firstName, :lastName, :password, :password_confirmation, :remember_me, :company, :status_type, :email, :avatar, :avatar_cache)}
      devise_parameter_sanitizer.for(:account_update){ |u| u.permit(:firstName, :lastName, :password, :password_confirmation, :current_password, :remember_me, :company, :status_type, :email, :avatar, :avatar_cache, :remove_avatar)}
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :find_job, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only:[:new, :create, :edit, :update, :destroy]
  before_filter :check_user, only:[:edit, :update, :destroy]
  
  def index
    @user = User.all
    if params[:category].blank?
      @jobs = Job.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @jobs = Job.where(category_id: @category_id).order("created_at DESC")
    end
  end

  def show
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(jobs_params)
    @job.user_id = current_user.id

    if @job.save
      redirect_to @job, notice: "Job has been created!"
    else
      render "new", notice: "Job was unable to save post!"
    end
  end

  def edit
  end

  def update
    if @job.update jobs_params
      redirect_to @job, notice: "Updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @job.destroy
    redirect_to root_path
  end

  private
    def jobs_params
      params.require(:job).permit(:title, :description, :city, :slug, :category_id)
    end

    def check_user
      if current_user != @job.user
        redirect_to root_url, alert: "This job post isn't yours!!"
      end
    end

    def find_job
      @job = Job.friendly.find(params[:id])
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
  <% if @job.errors.any? %>
  <h2><%= pluralize(@job.errors.count, "error") %> prevent this post from saving: </h2>
  <ul>
    <% @job.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

  <form>
    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description, "Job Description" %><br>
      <%= f.text_area :description, class: "form-control", rows: "12"%>
    </div>

    <div class="form-group">
      <%= f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a category"} %>
    </div>

    <div class="form-group">
      <%= f.label :city %><br>
      <%= f.text_field :city, class: "form-control" %>
    </div>

    <%= f.submit class: "btn btn-primary" %>
  </form>

<% end %>

<form>

app/views/jobs/edit.html.erb
<h1> Edit </h1>
<%= render 'form' %>

app/views/jobs/index.html.erb
  <% if (user_signed_in?) && (current_user.status_type == "Employer" ) %> 
    <i class="fa fa-pencil" aria-hidden="true"><%= link_to "new", new_job_path %></i>
  <% end %>


<ul id="timeline">
  <% @jobs.each do |job| %>
    <a href="#">
    <li class="listing clearfix">
      <div class="image_wrapper">
        <%= image_tag job.user.avatar.url(:thumb)%>
      </div>
      <div class="info">
        <span class="job_title"><h5><%= link_to job.title, job %></h5></span>
        <span class="job_info"> <%= job.user.company %> <span>&bull;</span> <%= job.city %> <span>&bull;</span> <%= job.created_at.strftime("%A, %b, %d") %></span>
      </div>
      <% if job.category_id == "1" %>
        <span class="job_type full_time">Full-Time</span> 
      <% elsif job.category_id == "2" %>
        <span class="job_type part_time">Part-Time</span>
      <% elsif job.category_id == "3" %>
        <span class="job_type freelance">Freelance</span>
      <% else %>
        <span class="job_type contract">Contract</span>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/jobs/new.html.erb
<h1>New</h1>
<%= render 'form' %>

app/views/jobs/show.html.erb
<div class="sub_nav">
  <% if (user_signed_in?) && (current_user == @job.user ) %> 

    <i class="fa fa-pencil" aria-hidden="true"><%= link_to "Edit", edit_job_path %></i> | <i class="fa fa-trash-o" aria-hidden="true">
<%= link_to "Delete", job_path(@job), method: :delete, data:{confirm: "Are you sure?"} %></i>
  <% end %>
</div>

<div class="job_post">
  <h6 id="date"><%= @job.created_at.strftime("%A, %b, %d") %></h6>
  <h1 id="title"><%= @job.title %></h1>
  <hr>
  <h5 id="job_info">&bull;<%= @job.user.company %> &bull;<%= @job.city %> &bull;

    <% if @job.category_id == "1" %>
      <span class="job_type full_time">Full-Time</span> 
    <% elsif @job.category_id == "2" %>
      <span class="job_type part_time">Part-Time</span>
    <% elsif @job.category_id == "3" %>
      <span class="job_type freelance">Freelance</span>
    <% else %>
      <span class="job_type contract">Contract</span>
    <% end %>

  </h5>

  <p id="job_contents"><%= @job.description %> </p>
</div>
<hr>
<div id="share_box">
  <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @job.title%> by @WebDeveloper.io - &amp;url<%= url_for([@job,{only_path: false}]) %>', '_blank', 'width=800,height=500,top=200,left=300');void(0);">
      <i class="fa fa-twitter"></i>
    </a>
    
    <a onclick="javascript:window.open('http://facebook.com/sharer.php?u=<%= url_for([@job,{only_path: false}]) %>', '_blank', 'width=800,height=500,top=200,left=300');void(0);">
      <i class="fa fa-facebook"></i>
    </a>

    <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@job,{only_path: false}]) %>', '_blank', 'width=800,height=500,top=200,left=300');void(0);">
      <i class="fa fa-google-plus"></i>
    </a>
</div>
<hr>

<%= link_to "< Previous", root_path %>

app/views/layouts/_navbar.html.erb
<header>
  <div class="logo">
    <%= image_tag("logo.png") %>
  </div>

  <nav class="nav">
    <a href="/jobs">All Job</a>
    <% Category.all.each do |category| %>
      <%= link_to category.name, jobs_path(category: category.name)%>
    <% end %>
  </nav>

</header>

app/views/layouts/_users.html.erb
<div class="menu">
  <% if user_signed_in? %>
    <%= link_to "Edit", edit_user_registration_path %> | <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
  <% else %>
    <a href="/login"><i class="fa fa-sign-in fa-lg" aria-hidden="true"></i></a>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prototypev3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    "https://cdnjs.cloudflare.com/ajax/libs/normalize/4.1.1/normalize.min.css" %>
  <%= stylesheet_link_tag    "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="border"></div>
  <div class="wrapper">
    <%= render 'layouts/users' %>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>

</body>
</html>